// --- Utility Functions ---
function deepCopy(obj) { if (obj === null || typeof obj !== 'object') return obj; if (obj instanceof Date) return new Date(obj); if (Array.isArray(obj)) return obj.map(deepCopy); const copiedObject = {}; for (const key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { copiedObject[key] = deepCopy(obj[key]); } } return copiedObject;}
function generateId(prefix = 'id_') { return prefix + Date.now().toString(36) + Math.random().toString(36).substr(2, 5); }

// --- Alpine.js Application ---
function plannerApp() {
  const PB_BASE_URL = '/'; 
  const pb = new PocketBase(PB_BASE_URL);
  pb.autoCancellation(false);

  let isInitializing = true;
  let lastSavedState = null;
  let appDefaults = null; 

  const DefaultDataManager = { 
    configKey: "default_v1", data: null, error: null,
    async fetch() { 
        this.error = null; try { this.data = await pb.collection('app_config').getFirstListItem(`config_key="${this.configKey}"`); if (!this.data) { this.error = "Default application configuration (app_config) not found in PocketBase."; throw new Error(this.error); } console.log("App defaults fetched successfully."); } catch (error) { console.error("Fatal Error: Could not initialize app defaults from PocketBase:", error); this.error = error.message || "Failed to load app settings from PocketBase."; this.data = null; } appDefaults = this.data; return this.data;
    },
    getPlannerTitle: function() { return this.data?.planner_title_default; },
    getUiConfig: function() { return deepCopy(this.data?.ui_config_default); },
    getTimes: function() { return deepCopy(this.data?.times_default); },
    getSchedule: function() { const s = deepCopy(this.data?.schedule_default); (s||[]).forEach(i=>{i.id=i.id||generateId('sec_');(i.activities||[]).forEach(a=>{if(!a.id)a.id=generateId('act_');if(!a.streaks)a.streaks={ mon:0, tue:0, wed:0, thu:0, fri:0, sat:0, sun:0, current:0, longest:0 };});}); return s;},
    getTasksCount: function() { return this.data?.tasks_default_count || 0; },
    getWorkoutPlan: function() { const p = deepCopy(this.data?.workout_plan_default); (p||[]).forEach(d=>{d.id=d.id||generateId('wpd_');(d.exercises||[]).forEach(e=>{if(!e.id)e.id=generateId('ex_');});}); return p;},
    getMeals: function() { const m = deepCopy(this.data?.meals_default); (m||[]).forEach(i=>{if(!i.id)i.id=generateId('meal_');}); return m;},
    getGroceryList: function() { const l = deepCopy(this.data?.grocery_list_default); (l||[]).forEach(c=>{if(!c.id)c.id=generateId('gcat_');}); return l;},
    getGroceryBudgetPlaceholder: function() { return this.data?.grocery_budget_default_placeholder; },
    getBodyMeasurements: function() { const b = deepCopy(this.data?.body_measurements_default); (b||[]).forEach(i=>{if(!i.id)i.id=generateId('bm_');}); return b;},
    getFinancials: function() { const f = deepCopy(this.data?.financials_default); (f||[]).forEach(i=>{if(!i.id)i.id=generateId('fin_');}); return f;}
  };
  
  const DateTimeUtils = { 
    getCurrentIsoWeek:()=> {const n=new Date(),d=new Date(Date.UTC(n.getFullYear(),n.getMonth(),n.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return`${d.getUTCFullYear()}-W${Math.ceil(((d-y)/864e5+1)/7).toString().padStart(2,"0")}`;},parseISOWeek:(s)=>{if(!/^\d{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$/.test(s))return new Date();const[y,w]=s.split("-"),W=parseInt(w.substring(1)),d=new Date(Date.UTC(parseInt(y),0,1+(W-1)*7)),D=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-D+1);return d;},getWeekDateRange:(d)=>{const s=new Date(d),e=new Date(s);e.setUTCDate(s.getUTCDate()+6);return`${DateTimeUtils.formatDate(s)}-${DateTimeUtils.formatDate(e)}`;},formatDate:(d)=>`${(d.getUTCMonth()+1).toString().padStart(2,"0")}/${d.getUTCDate().toString().padStart(2,"0")}`,formatShortDate:(i)=>{const n=new Date();n.setDate(n.getDate()+i);return`${n.getMonth()+1}/${n.getDate()}`;},formatPrayerTime:(s)=>{if(!s||typeof s!=="string")return"";const t=s.split(" ")[0],[h,m]=t.split(":");if(!h||!m)return"";let H=parseInt(h),M=parseInt(m);if(isNaN(H)||isNaN(M)||H<0||H>23||M<0||M>59)return"";const A=H>=12?"PM":"AM";H%=12;H=H||12;return`${H}:${M.toString().padStart(2,"0")}${A}`;},calculateQiyamTime:(f)=>{if(!f||typeof f!=="string")return"";const p=f.split(" ")[0].split(":");if(p.length<2)return"";let H=parseInt(p[0]),M=parseInt(p[1]);if(isNaN(H)||isNaN(M)||H<0||H>23||M<0||M>59)return"";let q=new Date();q.setHours(H,M,0,0);q.setHours(q.getHours()-1);return`${q.getHours().toString().padStart(2,"0")}:${q.getMinutes().toString().padStart(2,"0")}`;},
  };
  
  return {
    currentWeek: '', dateRange: '', saveStatus: 'saved', isOnline: navigator.onLine, pendingSync: [],
    showNotification: false, notificationMessage: '', showWeekSelector: false,
    dropdownPosition: { top: 0, left: 0 }, currentDay: (new Date()).getDay(),
    plannerTitle: 'Loading Planner...', uiConfig: {}, times: [], schedule: [], tasks: [], workoutPlan: [],
    meals: [], groceryBudget: '', groceryList: [], bodyMeasurements: [], financials: [],
    savedWeeks: [], saveDataTimeout: null, notificationTimeout: null,

    async init() {
      isInitializing = true; console.log("App init starting...");
      await DefaultDataManager.fetch(); 
      if (DefaultDataManager.error) { this.showErrorMessage(`CRITICAL: ${DefaultDataManager.error}. Defaults not loaded. Ensure 'app_config' is populated. Seeder utility may be needed.`); this.plannerTitle = "Planner Config Error"; }
      else { this.plannerTitle = DefaultDataManager.getPlannerTitle() || "Weekly Planner"; }
      
      window.addEventListener('online', () => { this.isOnline = true; this.syncPendingData(); });
      window.addEventListener('offline', () => this.isOnline = false);
      document.addEventListener('click',e=>{if(!e.target.closest('.dropdown')&&!e.target.closest('.clickable')){this.showWeekSelector=false;}});
      this.pendingSync = JSON.parse(localStorage.getItem('planner_pending_sync') || '[]');
      this.currentWeek = DateTimeUtils.getCurrentIsoWeek();
      this.dateRange = DateTimeUtils.getWeekDateRange(DateTimeUtils.parseISOWeek(this.currentWeek));
      await this.loadWeek(this.currentWeek, true); 
      if (appDefaults && !DefaultDataManager.error) { setInterval(() => { if (!isInitializing && this.hasSignificantChanges()) this.saveData(); }, 30000); }
      if (this.isOnline) this.syncPendingData();
      console.log("App init finished.");
    },

    applyDefaults() {
      if (!appDefaults || DefaultDataManager.error) { console.warn("applyDefaults: Defaults error. Minimal structures."); this.plannerTitle=appDefaults?.planner_title_default||"Planner (No Config)";this.uiConfig=appDefaults?.ui_config_default||{};this.times=(appDefaults?.times_default||[]).map(t=>({...t}));this.schedule=(appDefaults?.schedule_default||[]).map(s=>({...s,id:s.id||generateId('sec_'),activities:(s.activities||[]).map(a=>({...a,id:a.id||generateId('act_'),streaks:a.streaks||{ mon:0,tue:0,wed:0,thu:0,fri:0,sat:0,sun:0,current:0,longest:0 }}))}));this.tasks=Array(appDefaults?.tasks_default_count||20).fill(null).map((_,i)=>({id:generateId('task_'),num:'',priority:'',tag:'',description:'',date:'',completed:''}));this.workoutPlan=(appDefaults?.workout_plan_default||[]).map(d=>({...d,id:d.id||generateId('wpd_'),exercises:(d.exercises||[]).map(e=>({...e,id:e.id||generateId('ex_')}))}));this.meals=(appDefaults?.meals_default||[]).map(m=>({...m,id:m.id||generateId('meal_')}));this.groceryList=(appDefaults?.grocery_list_default||[]).map(g=>({...g,id:g.id||generateId('gcat_')}));this.groceryBudget=appDefaults?.grocery_budget_default_placeholder||'';this.bodyMeasurements=(appDefaults?.body_measurements_default||[]).map(b=>({...b,id:b.id||generateId('bm_')}));this.financials=(appDefaults?.financials_default||[]).map(f=>({...f,id:f.id||generateId('fin_')})); return; }
      this.plannerTitle=DefaultDataManager.getPlannerTitle()||"Weekly Planner";this.uiConfig=DefaultDataManager.getUiConfig()||{};this.times=DefaultDataManager.getTimes()||[];this.schedule=DefaultDataManager.getSchedule()||[];this.tasks=Array(DefaultDataManager.getTasksCount()||20).fill(null).map((_,i)=>({id:generateId('task_'),num:'',priority:'',tag:'',description:'',date:'',completed:''}));this.workoutPlan=DefaultDataManager.getWorkoutPlan()||[];this.meals=DefaultDataManager.getMeals()||[];this.groceryList=DefaultDataManager.getGroceryList()||[];this.groceryBudget=DefaultDataManager.getGroceryBudgetPlaceholder()||'';this.bodyMeasurements=DefaultDataManager.getBodyMeasurements()||[];this.financials=DefaultDataManager.getFinancials()||[];
    },
    populateFieldsFromSaved(savedData) {
        const getDef=(fn,eV=undefined)=>appDefaults?fn.call(DefaultDataManager):eV;
        this.plannerTitle=savedData.planner_title||getDef(DefaultDataManager.getPlannerTitle,"Weekly Planner (Saved)");this.uiConfig=deepCopy(savedData.ui_config||getDef(DefaultDataManager.getUiConfig,{}));this.times=deepCopy(savedData.times_display||getDef(DefaultDataManager.getTimes,[]));
        const defSched=getDef(DefaultDataManager.getSchedule,[]);this.schedule=(savedData.schedule_data||defSched).map((s,sIdx)=>{const defSect=(defSched||[])[sIdx]||{id:generateId('sec_'),activities:[]};return{...defSect,...s,id:s.id||defSect.id,activities:(s.activities||defSect.activities||[]).map((a,aIdx)=>{const defAct=(defSect.activities||[])[aIdx]||{};return{...defAct,...a,id:a.id||defAct.id||generateId('act_'),streaks:a.streaks||defAct.streaks||{mon:0,tue:0,wed:0,thu:0,fri:0,sat:0,sun:0,current:0,longest:0}};})};});
        const defTaskCnt=getDef(DefaultDataManager.getTasksCount,20);const taskCnt=(savedData.tasks_data?.length>=defTaskCnt)?savedData.tasks_data.length:defTaskCnt;this.tasks=Array(taskCnt).fill(null).map((_,i)=>{const sT=savedData.tasks_data?.[i];const defT=(appDefaults?.tasks_default||[])[i]||{};return{id:sT?.id||defT.id||generateId('task_'),num:this.validateValue(sT?.num||defT.num),priority:this.validateValue(sT?.priority||defT.priority),tag:this.validateValue(sT?.tag||defT.tag),description:this.validateValue(sT?.description||defT.description),date:this.validateValue(sT?.date||defT.date),completed:this.validateValue(sT?.completed||defT.completed)};});
        const defWP=getDef(DefaultDataManager.getWorkoutPlan,[]);this.workoutPlan=(savedData.workout_plan_data||defWP).map((d,dIdx)=>{const defDay=(defWP||[])[dIdx]||{id:generateId('wpd_'),exercises:[]};return{...defDay,...d,id:d.id||defDay.id,exercises:(d.exercises||defDay.exercises||[]).map((e,eIdx)=>{const defEx=(defDay.exercises||[])[eIdx]||{};return{...defEx,...e,id:e.id||defEx.id||generateId('ex_')};})};});
        const defM=getDef(DefaultDataManager.getMeals,[]);this.meals=(savedData.meals_data||defM).map((m,mIdx)=>{const defMItem=(defM||[])[mIdx]||{};return{...defMItem,...m,id:m.id||defMItem.id||generateId('meal_')};});
        this.groceryBudget=this.validateValue(savedData.grocery_budget||getDef(DefaultDataManager.getGroceryBudgetPlaceholder,''));
        const defGL=getDef(DefaultDataManager.getGroceryList,[]);this.groceryList=(savedData.grocery_list_data||defGL).map((g,gIdx)=>{const defG=(defGL||[])[gIdx]||{};return{...defG,...g,id:g.id||defG.id||generateId('gcat_')};});
        const defBM=getDef(DefaultDataManager.getBodyMeasurements,[]);this.bodyMeasurements=(savedData.body_measurements_data||defBM).map((b,bIdx)=>{const defB=(defBM||[])[bIdx]||{};return{...defB,...b,id:b.id||defB.id||generateId('bm_')};});
        const defFin=getDef(DefaultDataManager.getFinancials,[]);this.financials=(savedData.financials_data||defFin).map((f,fIdx)=>{const defF=(defFin||[])[fIdx]||{};return{...defF,...f,id:f.id||defF.id||generateId('fin_')};});
        lastSavedState=JSON.stringify(this.getCurrentDataStateForPersistence());
    },
    async loadWeek(isoWeek,isInitLoad=false){if(!appDefaults&&isInitLoad){await DefaultDataManager.fetch();if(DefaultDataManager.error){this.showErrorMessage(`CRITICAL: ${DefaultDataManager.error}. Cannot load week.`);if(isInitLoad)isInitializing=false;return;}}
    if(!appDefaults){this.showErrorMessage("Critical error: App defaults not loaded. Week load aborted.");if(isInitLoad)isInitializing=false;return;}
    if(!/^\d{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$/.test(isoWeek)){this.showErrorMessage("Invalid week format");if(isInitLoad)isInitializing=false;return;}
    this.showWeekSelector=false;this.currentWeek=isoWeek;this.dateRange=DateTimeUtils.getWeekDateRange(DateTimeUtils.parseISOWeek(isoWeek));let rec=null;
    if(this.isOnline){try{rec=await pb.collection('planners').getFirstListItem(`week_id="${isoWeek}"`);}catch(e){if(e.status!==404)console.error("PB load error:",e);}}
    if(!rec){const ld=localStorage.getItem(`planner_${isoWeek}`);if(ld)try{rec=JSON.parse(ld);}catch(e){console.error(`Local parse error ${isoWeek}:`,e);rec=null;}}
    if(rec){this.populateFieldsFromSaved(rec);}else{this.applyDefaults();}
    this.calculateScores();if(this.times.every(t=>!t.value)){await this.fetchAndSetPrayerTimes();}
    if(isInitLoad){isInitializing=false;console.log("Initial load process finished.");}},
    getCurrentDataStateForPersistence(){return{week_id:this.currentWeek,date_range:this.dateRange,planner_title:this.plannerTitle,ui_config:this.uiConfig,times_display:this.times,schedule_data:this.schedule,tasks_data:this.tasks,workout_plan_data:this.workoutPlan,meals_data:this.meals,grocery_budget:this.groceryBudget,grocery_list_data:this.groceryList,body_measurements_data:this.bodyMeasurements,financials_data:this.financials};},
    saveData(){if(isInitializing)return;if(this.saveDataTimeout)clearTimeout(this.saveDataTimeout);this.saveStatus='saving';this.saveDataTimeout=setTimeout(async()=>{try{this.calculateScores();const data=this.getCurrentDataStateForPersistence();localStorage.setItem(`planner_${this.currentWeek}`,JSON.stringify(data));if(this.isOnline){await this.saveToPocketbase(this.currentWeek,data);this.pendingSync=this.pendingSync.filter(it=>!(it.weekId===this.currentWeek&&it.operation==='save'));localStorage.setItem('planner_pending_sync',JSON.stringify(this.pendingSync));}else{this.addToPendingSync(this.currentWeek,data,'save');}lastSavedState=JSON.stringify(data);this.saveStatus='saved';}catch(e){console.error("SaveData error:",e);this.saveStatus='error';this.showErrorMessage("Error saving: "+e.message);setTimeout(()=>this.saveStatus='saved',3000);}},750);},
    hasSignificantChanges(){if(isInitializing)return false;if(!lastSavedState)return true;return JSON.stringify(this.getCurrentDataStateForPersistence())!==lastSavedState;},
    addToPendingSync(wId,data,op='save'){this.pendingSync=this.pendingSync.filter(it=>!(it.weekId===wId&&it.operation===op));this.pendingSync.push({weekId:wId,data:data?deepCopy(data):null,operation:op,timestamp:new Date().toISOString()});localStorage.setItem('planner_pending_sync',JSON.stringify(this.pendingSync));},
    async syncPendingData(){if(!this.isOnline||this.pendingSync.length===0)return;const items=[...this.pendingSync];let curPend=[...this.pendingSync];for(const item of items){try{if(item.operation==='delete'){await this.deleteFromPocketbase(item.weekId);}else{await this.saveToPocketbase(item.weekId,item.data);}curPend=curPend.filter(i=>i.timestamp!==item.timestamp);}catch(e){console.error("Sync error:",item,e);}}this.pendingSync=curPend;localStorage.setItem('planner_pending_sync',JSON.stringify(this.pendingSync));},
    async saveToPocketbase(wId,data){try{const ex=await pb.collection('planners').getFirstListItem(`week_id="${wId}"`).catch(e=>{if(e.status===404)return null;throw e;});if(ex){await pb.collection('planners').update(ex.id,data);}else{await pb.collection('planners').create(data);}}catch(e){console.error(`PB save error ${wId}:`,e,"Data:",data);throw e;}},
    async deleteFromPocketbase(wId){try{const ex=await pb.collection('planners').getFirstListItem(`week_id="${wId}"`).catch(e=>{if(e.status===404)return null;throw e;});if(ex)await pb.collection('planners').delete(ex.id);}catch(e){console.error(`PB delete error ${wId}:`,e);throw e;}},
    editInline(event,type,index,defaultValue=''){const el=event.currentTarget;const origTxt=el.innerText;const isTA=['mealIngredients','groceryCategoryItems'].includes(type);const inp=document.createElement(isTA?'textarea':'input');inp.type='text';inp.value=defaultValue;inp.className=isTA?'inline-edit-textarea':'inline-edit-input';if(isTA)inp.rows=3;el.innerHTML='';el.appendChild(inp);inp.focus();inp.select();const saveIt=()=>{const newVal=inp.value;let sIdxMap=-1;if(type==='sectionName'||(typeof index==='object'&&index!==null&&typeof index.sIdx==='number')){sIdxMap=this.schedule.length-1-(typeof index==='object'?index.sIdx:index);}
    switch(type){case'plannerTitle':this.plannerTitle=newVal;break;case'timeLabel':if(this.times[index])this.times[index].label=newVal;break;case'sectionName':if(sIdxMap!==-1&&this.schedule[sIdxMap])this.schedule[sIdxMap].name=newVal;break;case'activityPrefix':if(sIdxMap!==-1&&this.schedule[sIdxMap]?.activities[index.aIdx]){const a=this.schedule[sIdxMap].activities[index.aIdx];const p=a.name.split(':');a.name=newVal.trim()+(p.length>1?':'+p.slice(1).join(':').trimStart():'');}break;case'activityName':if(sIdxMap!==-1&&this.schedule[sIdxMap]?.activities[index.aIdx]){const a=this.schedule[sIdxMap].activities[index.aIdx];const p=a.name.split(':');a.name=(p.length>1&&p[0].trim()?p[0].trim()+': ':'')+newVal;}break;case'maxValue':if(sIdxMap!==-1&&this.schedule[sIdxMap]?.activities[index.aIdx]?.days[index.day]){this.schedule[sIdxMap].activities[index.aIdx].days[index.day].max=parseInt(newVal)||0;}break;case'maxScore':if(sIdxMap!==-1&&this.schedule[sIdxMap]?.activities[index.aIdx]){this.schedule[sIdxMap].activities[index.aIdx].maxScore=parseInt(newVal)||0;}break;case'sectionTitle':if(this.uiConfig.sectionTitles&&this.uiConfig.sectionTitles[index]!==undefined)this.uiConfig.sectionTitles[index]=newVal;break;case'mainTableHeader':if(this.uiConfig.mainTableHeaders&&this.uiConfig.mainTableHeaders[index]!==undefined)this.uiConfig.mainTableHeaders[index]=newVal;break;case'dayHeader':if(this.uiConfig.dayHeaders&&this.uiConfig.dayHeaders[index]!==undefined)this.uiConfig.dayHeaders[index]=newVal;break;case'maxHeader':if(this.uiConfig.maxHeaders&&this.uiConfig.maxHeaders[index]!==undefined)this.uiConfig.maxHeaders[index]=newVal;break;case'taskHeader':if(this.uiConfig.taskHeaders&&this.uiConfig.taskHeaders[index]!==undefined)this.uiConfig.taskHeaders[index]=newVal;break;case'workoutDayName':if(this.workoutPlan[index])this.workoutPlan[index].name=newVal;break;case'exercisePrefix':if(this.workoutPlan[index.dayIdx]?.exercises[index.exIdx]){this.workoutPlan[index.dayIdx].exercises[index.exIdx].prefix=newVal;}break;case'exerciseName':if(this.workoutPlan[index.dayIdx]?.exercises[index.exIdx]){this.workoutPlan[index.dayIdx].exercises[index.exIdx].name=newVal;}break;case'mealName':if(this.meals[index])this.meals[index].name=newVal;break;case'mealIngredients':if(this.meals[index])this.meals[index].ingredients=newVal;break;case'groceryCategoryName':if(this.groceryList[index])this.groceryList[index].name=newVal;break;case'groceryCategoryItems':if(this.groceryList[index])this.groceryList[index].items=newVal;break;case'measurementName':if(this.bodyMeasurements[index])this.bodyMeasurements[index].name=newVal;break;case'financialName':if(this.financials[index])this.financials[index].name=newVal;break;case'financialAccount':if(this.financials[index])this.financials[index].account=newVal;break;}
    if(inp.parentNode===el)el.removeChild(inp);el.innerText=newVal||origTxt;this.saveData();};const onKD=(e)=>{if(e.key==='Enter'&&!isTA){cleanSave();e.preventDefault();}else if(e.key==='Escape'){cleanRestore();}};const cleanSave=()=>{inp.removeEventListener('blur',cleanSave);inp.removeEventListener('keydown',onKD);saveIt();};const cleanRestore=()=>{inp.removeEventListener('blur',cleanSave);inp.removeEventListener('keydown',onKD);if(inp.parentNode===el)el.removeChild(inp);el.innerText=origTxt;};inp.addEventListener('blur',cleanSave);inp.addEventListener('keydown',onKD);},
    toggleTaskCompletion(task){task.completed=task.completed==='✓'?'☐':'✓';this.saveData();},showErrorMessage(msg){this.notificationMessage=msg;this.showNotification=true;if(this.notificationTimeout)clearTimeout(this.notificationTimeout);this.notificationTimeout=setTimeout(()=>this.showNotification=false,7000);},validateValue(val,isNum=false,min=null,max=null){const sVal=String(val||'');if(sVal.trim()==='')return'';if(isNum){constn=parseFloat(sVal);if(isNaN(n))return'';if(min!==null&&n<min)return min.toString();if(max!==null&&n>max)return max.toString();return n.toString();}return sVal;},validateTextInput(e){this.saveData();},validateNumberInput(e){this.calculateScores();this.saveData();},
    calculateScores(){if(!this.schedule||this.schedule.length===0)return;const dT={mon:0,tue:0,wed:0,thu:0,fri:0,sat:0,sun:0};const dK=['mon','tue','wed','thu','fri','sat','sun'];this.schedule.forEach(s=>{if(s.name==='TOTAL')return;(s.activities||[]).forEach(a=>{let aS=0;Object.entries(a.days||{}).forEach(([d,dD])=>{if(!dD)return;const v=parseInt(dD.value)||0;const mV=parseInt(dD.max)||0;if(v>0&&mV>0){dT[d]=(dT[d]||0)+Math.min(v,mV);aS+=Math.min(v,mV);}dD.value=v===0?'':v.toString();});a.score=aS;if(!a.streaks)a.streaks={mon:0,tue:0,wed:0,thu:0,fri:0,sat:0,sun:0,current:0,longest:0};const tI=this.currentDay===0?6:this.currentDay-1;let cS=0;for(let i=0;i<7;i++){const dTI=(tI-i+7)%7;const dk=dK[dTI];if(a.days[dk]&&(parseInt(a.days[dk].value)||0)>0&&(parseInt(a.days[dk].max)||0)>0){cS++;}else if(a.days[dk]&&(parseInt(a.days[dk].max)||0)>0){break;}}a.streaks.current=cS;a.streaks.longest=Math.max(a.streaks.longest||0,cS);});});const tS=this.schedule.find(s=>s.name==='TOTAL');if(tS?.activities?.[0]){const tA=tS.activities[0];let gTS=0;let gTMS=0;dK.forEach(d=>{let dM=0;this.schedule.forEach(s=>{if(s.name!=='TOTAL'){(s.activities||[]).forEach(act=>{if(act.days[d]&&act.days[d].max){dM+=parseInt(act.days[d].max)||0;}});}});if(tA.days[d])tA.days[d].max=dM;});Object.entries(dT).forEach(([d,tot])=>{if(tA.days[d])tA.days[d].value=tot.toString();gTS+=tot;});tA.score=gTS;this.schedule.forEach(s=>{if(s.name!=='TOTAL'){(s.activities||[]).forEach(act=>gTMS+=(parseInt(act.maxScore)||0));}});tA.maxScore=gTMS;}},
    async fetchAndSetPrayerTimes(){ console.log("Fetching prayer times for London (fixed)"); await this.fetchPrayerTimesForCoords(51.5074, -0.1278, "London (Default)"); },
    async fetchPrayerTimesForCoords(lat,lon,cityName="Selected Location"){const tD=new Date(),d=tD.getDate(),m=tD.getMonth()+1,y=tD.getFullYear();const cK=`prayer_times_${y}_${m}_${d}_${lat.toFixed(2)}_${lon.toFixed(2)}`;constcD=localStorage.getItem(cK);if(cD){try{this.setPrayerTimesDisplay(JSON.parse(cD));return;}catch(e){localStorage.removeItem(cK);}}try{const r=await fetch(`https://api.aladhan.com/v1/calendar/${y}/${m}?latitude=${lat}&longitude=${lon}&method=2`);if(!r.ok)throw new Error(`Aladhan API error: ${r.statusText}(${r.status})`);const aD=await r.json();if(aD.code===200&&aD.data?.[d-1]?.timings){const T=aD.data[d-1].timings;localStorage.setItem(cK,JSON.stringify(T));this.setPrayerTimesDisplay(T);}else throw new Error("Invalid Aladhan API data");}catch(e){console.error("Fetch prayer times error for "+cityName+":",e);this.showErrorMessage(`Failed to fetch prayer times for ${cityName}. Defaults used.`);this.setPrayerTimesDisplay({Fajr:"05:30",Dhuhr:"12:30",Asr:"15:45",Maghrib:"18:30",Isha:"20:00"});}},
    setPrayerTimesDisplay(T){const Q=DateTimeUtils.calculateQiyamTime(T.Fajr);const M={Q:Q,F:T.Fajr,D:T.Dhuhr,A:T.Asr,M:T.Maghrib,I:T.Isha};let C=false;this.times.forEach(ts=>{const nT=DateTimeUtils.formatPrayerTime(M[ts.label]);if(ts.value!==nT){ts.value=nT;C=true;}});if(C&&!isInitializing)this.saveData();},
    fetchSavedWeeks(){const wD=new Map();const cIW=DateTimeUtils.getCurrentIsoWeek();const aUW=(iso,dr,src,isC)=>{const ex=wD.get(iso);const nDR=dr||DateTimeUtils.getWeekDateRange(DateTimeUtils.parseISOWeek(iso));if(!ex||(src==='pocketbase'&&ex.source!=='pocketbase')||(src==='local'&&ex.source==='current')){wD.set(iso,{iso_week:iso,dateRange:nDR,source:src,isCurrent:isC});}else if(ex&&!ex.dateRange&&nDR){ex.dateRange=nDR;}};aUW(cIW,DateTimeUtils.getWeekDateRange(DateTimeUtils.parseISOWeek(cIW)),'current',true);const uD=()=>{this.savedWeeks=Array.from(wD.values()).sort((a,b)=>(a.isCurrent&&!b.isCurrent)?-1:(!a.isCurrent&&b.isCurrent)?1:b.iso_week.localeCompare(a.iso_week));};if(this.isOnline){pb.collection('planners').getFullList({sort:'-week_id',fields:'week_id,date_range'}).then(r=>{r.forEach(it=>aUW(it.week_id,it.date_range,'pocketbase',it.week_id===cIW));uD();}).catch(e=>{console.error("PB fetch saved weeks error:",e);for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('planner_')&&!k.includes('pending_sync')){const iw=k.replace('planner_','');try{const d=JSON.parse(localStorage.getItem(k));aUW(iw,d.date_range,'local',iw===cIW);}catch(le){}}}uD();});}else{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('planner_')&&!k.includes('pending_sync')){const iw=k.replace('planner_','');try{const d=JSON.parse(localStorage.getItem(k));aUW(iw,d.date_range,'local',iw===cIW);}catch(e){}}}uD();}},
    confirmLoadWeek(isoWeek){if(this.hasSignificantChanges()&&isoWeek!==this.currentWeek){if(confirm("Unsaved changes. Load anyway?"))this.loadWeek(isoWeek);}else{this.loadWeek(isoWeek);}},confirmDeleteWeek(isoWeek){if(confirm(`Delete schedule for ${isoWeek}?`))this.deleteWeek(isoWeek);},async deleteWeek(isoWeek){localStorage.removeItem(`planner_${isoWeek}`);if(this.isOnline){try{await this.deleteFromPocketbase(isoWeek);}catch(e){this.addToPendingSync(isoWeek,null,'delete');}}else{this.addToPendingSync(isoWeek,null,'delete');}this.savedWeeks=this.savedWeeks.filter(w=>w.iso_week!==isoWeek);if(this.currentWeek===isoWeek){this.currentWeek=DateTimeUtils.getCurrentIsoWeek();await this.loadWeek(this.currentWeek);}}
  };
}
